### ISSUE TITLE
Bug report: erro 500 ao visitar unlock apoiado

### ISSUE THREAD

**Issue by obvio171** [danielweinmann/unlock#19]
Está dando erro 500 quando entro na página de "unlocks apoiados" da Laboriosa: https://unlock.fund/en-US/initiatives/10/contributions/446

Outras páginas de unlock apoiados abrem de boa. O erro só acontece quando estou logado. Se precisarem de ajuda para debugar, só falar. Valeu!

**Comment by danielweinmann** [comment]
Corrigido, Helder! Muito obrigado pelo report :D

Abração,
Daniel

**Comment by obvio171** [comment]
Valeu! =) Abraço!
